### ISSUE TITLE
gridwidth does not render in preview for jupyterlab_rise

### ISSUE THREAD

**Issue by Chilipp** [parmentelat/jupyterlab-gridwidth#15]
Hey! thanks a lot for this great project! I was waiting for somthing like this. I mainly used the splitcell-extension in presentations that I created with [rise](https://rise.readthedocs.io), there is just worked out-of-the-box. rise however now moved to [jupyterlab_rise](https://pypi.org/project/jupyterlab-rise/) and the developers explicitly stated in https://github.com/jupyterlab-contrib/rise/issues/1 that the `split-cell classic extension` is out-of-scope for `jupyterlab_rise` (which makes sense). I was hoping that`jupyterlab-gridwidth` fills this gap here, but it did not render the columns in the presentation (see right tab in the screenshot)

![image](https://github.com/parmentelat/jupyterlab-gridwidth/assets/9960249/6042898b-3591-49a6-a000-58d9e808b2ec)

To reproduce the setup here, you can use the example notebook from the [jupyter-contrib/rise repo](https://github.com/jupyterlab-contrib/rise) via

```bash
git clone https://github.com/jupyterlab-contrib/rise.git
cd rise
python -m venv venv
source venv/bin/activate
pip install jupyterlab jupyterlab_rise jupyterlab-gridwidth
jupyter server extension enable jupyterlab_rise
jupyter server extension enable jupyterlab-gridwith
```

start the server via `jupyter lab` and open the notebook at `examples/README.ipynb`

I am not an expert with developing externsions for jupyterlab. But do you think, such a `rise`-setup can be supported by `jupyterlab-gridwidth`? Or is this out-of-scope for your package?

thanks again for your efforts in this!

**Comment by parmentelat** [comment]
hey there !
nice to see that this tool can be useful

as far as rise: I made a very rough first diagnosis and it seems that the cell tag 'gridwidth-1-2' does not get applied as a css class on the html element

mind you: the lib actually responsible for applying css classes based on cell tags is actually
parmentelat/jupyterlab-celltagsclasses
so this is probably where the conversation should take place

will follow-up there

**Comment by parmentelat** [comment]
on a side note, I don't think you need to explicitly do these
```
jupyter server extension enable jupyterlab_rise
jupyter server extension enable jupyterlab-gridwith
```

as in my case at least the `pip install ..`s do the trick just fine
