### ISSUE TITLE
redefine keyboard shortcuts ?

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/jupyterlab-gridwidth#3]
as per @firezym the current choice of keyboard shortcuts is suboptimal as it is conflicting with predefined ones in the context of chrome/windows

**Comment by firezym** [comment]
Good idea. I am not sure which one to use. Maybe to align with `ctrl+shift+c` in windows, I suggest you could consider `ctrl+shift+num` :)

**Comment by parmentelat** [comment]
I'd rather stay way from `ctrl+shift` combos, as this tends to hurt my left pinky rather badly over time :)
would it make sense to use Alt instead of Ctrl - everything else being equal
for example can you bind `Alt-\ Alt-1 Alt-2` 
are there any foreseeable conflicts if we we go down this road ?

**Comment by firezym** [comment]
You are totally right lol... `ctrl+shift+num` is too painful for hands >.<
I have checked that `alt+num` is not occupied currently by windows chrome or windows system. I don't see much trending to asign `alt+num` as core hotkeys for chrome or windows. Conflicts might not be a near future problem :) 
We could go down this road and it's very convinient and smooth for hands!

**Comment by parmentelat** [comment]
all right, so that'll be the plan then
I will probably not have a chance to do this in the neat future though; I suggest for starters you do the binding of 1/2 locally on your setup, so you can have hands-on experience and comment back her to confirm it's a convenient enough choice

**Comment by firezym** [comment]
I am majorly focusing on data analysis, not familiar with frontend development, just start to learn about it. But I will try to play around it with you code. Thanks a lot for your implementation :)

**Comment by firezym** [comment]
#4 
Please check: hotkeys change from `ctrl+num` to `alt+num` pull request.

**Comment by parmentelat** [comment]
first step in this direction is made in #4 

let's see on the longer run if further work is needed to allow for more customization and cope with yet unforeseen setups

**Comment by parmentelat** [comment]
done in #4 and available in 0.1.3
