### ISSUE TITLE
behaviour is not perfect with multiple notebooks

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/jupyterlab-gridwidth#6]
as of 0.1.5:

the whole logic is broken, things need to be done on a per notebook basis and not globally

test scenerii (with settings = on)
- button must be found in all panels if jlab is restored with several notebooks open
- button must be created when a new notebook is opened later on
- the settings editor must act (turn off, then back on) on all open notebooks

**Comment by parmentelat** [comment]
0.1.6 attempts to improve the situation, but the situation is not 100% correct yet

**Comment by firezym** [comment]
I did not expect this serious bug >.<..

**Comment by firezym** [comment]
Thanks a lot for fixing this issue :)
