### ISSUE TITLE
Refreshing one notebook, another notebook's gridwidth effect will dissapear

### ISSUE THREAD

**Issue by firezym** [parmentelat/jupyterlab-gridwidth#8]
I recorded a gif as follows. A weird behavior (under newest version 0.2.1) ...
![动画](https://github.com/parmentelat/jupyterlab-gridwidth/assets/3654421/19ecfadc-e401-4272-85fc-92c9d9d19f5f)

**Comment by firezym** [comment]
If the gridwidth effect is ineffective, the button will change the metadata, but the cell width is locked to full width. The following is another gif screenshot with button clicked and cell metadata obeserved.
![动画](https://github.com/parmentelat/jupyterlab-gridwidth/assets/3654421/75b801a0-835f-422e-991d-bc67c969fb2d)

**Comment by parmentelat** [comment]
can you please run
```
pip install -U jupyterlab-celltagsclasses
```
and try again ?

**Comment by firezym** [comment]
Works fine now by upgrading jupyterlab-celltagsclasses :) Thanks a lot!
